In [1]:
print("all ok")

all ok


In [2]:
from sklearn.preprocessing import OneHotEncoder
import numpy

In [4]:
document = ["my name is Rajesh Karra and I love AI"]
document

['my name is Rajesh Karra and I love AI']

In [7]:
documents = ["people watch movie",
             "people watch cricket",
             "people like movie",
             "people like cricket"]
documents


['people watch movie',
 'people watch cricket',
 'people like movie',
 'people like cricket']

In [12]:
tokens = [sentence.lower().split() for sentence in document]

# This line iterates through each sentence in the 'document' variable.
# For each sentence, it converts all characters to lowercase using '.lower()' and then splits the sentence into a list of individual words (tokens) using '.split()'.
# The resulting list of word lists is then assigned to the 'tokens' variable.

In [9]:
tokens

[['my', 'name', 'is', 'rajesh', 'karra', 'and', 'i', 'love', 'ai']]

In [13]:
all_words = [[word] for sentence in tokens for word in sentence]
# This nested list comprehension iterates through each 'sentence' in the 'tokens' list.
# For each 'sentence', it then iterates through every 'word' within that sentence.
# It creates a new list containing just that 'word' ([word]) and appends it to the 'all_words' list.
# This effectively flattens the list of tokenized sentences into a single list where each word is in its own sublist.

In [14]:
all_words

[['my'],
 ['name'],
 ['is'],
 ['rajesh'],
 ['karra'],
 ['and'],
 ['i'],
 ['love'],
 ['ai']]

##### sparse_output=False means the encoder returns a NumPy array instead of a sparse matrix. This makes the output easier

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html

In [15]:
encoder = OneHotEncoder(sparse_output=False)

In [16]:
encoder.fit(all_words)

OneHotEncoder(sparse_output=False)

In [17]:
encoder.categories_

[array(['ai', 'and', 'i', 'is', 'karra', 'love', 'my', 'name', 'rajesh'],
       dtype=object)]

In [18]:
print("Vocabulary:", encoder.categories_[0])

Vocabulary: ['ai' 'and' 'i' 'is' 'karra' 'love' 'my' 'name' 'rajesh']


In [19]:
tokens

[['my', 'name', 'is', 'rajesh', 'karra', 'and', 'i', 'love', 'ai']]

In [20]:
for sentence in tokens:
    print(sentence)

['my', 'name', 'is', 'rajesh', 'karra', 'and', 'i', 'love', 'ai']


In [21]:
for sentence in tokens:
    encoded_sentence = encoder.transform([[word] for word in sentence])
    print("\nSentence:", sentence)
    print(encoded_sentence)


Sentence: ['my', 'name', 'is', 'rajesh', 'karra', 'and', 'i', 'love', 'ai']
[[0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]]


# BOW

###### https://scikit-learn.org/0.15/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

In [24]:
documents = ["people watch movie and watch movie again",
             "people watch cricket and watch cricket",
             "people like movie and like movie a lot",
             "people like cricket"]

In [25]:
document=["divesh is a good mentor he teaches us very well he teaches the project"]

AIM: Covert: Data: Number

In [26]:
bow = CountVectorizer()

In [27]:
bow_matrix =bow .fit_transform(document)

In [28]:
bow_matrix

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (1, 11)>

In [29]:
print("BOW Matrix:\n", bow_matrix.toarray())

BOW Matrix:
 [[1 1 2 1 1 1 2 1 1 1 1]]


In [30]:
bow.get_feature_names_out()

array(['divesh', 'good', 'he', 'is', 'mentor', 'project', 'teaches',
       'the', 'us', 'very', 'well'], dtype=object)

In [31]:
print("Vocabulary:", bow.get_feature_names_out())


Vocabulary: ['divesh' 'good' 'he' 'is' 'mentor' 'project' 'teaches' 'the' 'us' 'very'
 'well']


In [32]:
bow.fit(documents)

CountVectorizer()

In [33]:
documents

['people watch movie and watch movie again',
 'people watch cricket and watch cricket',
 'people like movie and like movie a lot',
 'people like cricket']

In [34]:
bow.transform(documents).toarray()

array([[1, 1, 0, 0, 0, 2, 1, 2],
       [0, 1, 2, 0, 0, 0, 1, 2],
       [0, 1, 0, 2, 1, 2, 1, 0],
       [0, 0, 1, 1, 0, 0, 1, 0]])

In [35]:
document = ["lion is the king of jungle"]

In [36]:
bow.transform(document)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 0 stored elements and shape (1, 8)>

# TF-IDF Practical

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [38]:
documents = ["people watch movie and watch movie again",
             "people watch cricket and watch cricket",
             "people like movie and like movie a lot",
             "people like cricket"]

In [39]:
tf_idf = TfidfVectorizer()

In [40]:
tf_idf_vector = tf_idf.fit_transform(documents)

In [41]:
tf_idf_vector

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 17 stored elements and shape (4, 8)>

In [42]:
tf_idf_vector.toarray()

array([[0.38771136, 0.24747114, 0.        , 0.        , 0.        ,
        0.61135218, 0.20232387, 0.61135218],
       [0.        , 0.2684707 , 0.66322944, 0.        , 0.        ,
        0.        , 0.21949239, 0.66322944],
       [0.        , 0.24747114, 0.        , 0.61135218, 0.38771136,
        0.61135218, 0.20232387, 0.        ],
       [0.        , 0.        , 0.64043405, 0.64043405, 0.        ,
        0.        , 0.42389674, 0.        ]])

In [43]:
for vector in tf_idf_vector.toarray():
    print(vector)

[0.38771136 0.24747114 0.         0.         0.         0.61135218
 0.20232387 0.61135218]
[0.         0.2684707  0.66322944 0.         0.         0.
 0.21949239 0.66322944]
[0.         0.24747114 0.         0.61135218 0.38771136 0.61135218
 0.20232387 0.        ]
[0.         0.         0.64043405 0.64043405 0.         0.
 0.42389674 0.        ]


In [44]:
tf_idf.get_feature_names_out()

array(['again', 'and', 'cricket', 'like', 'lot', 'movie', 'people',
       'watch'], dtype=object)

In [45]:
print("Vocabulary:", tf_idf.get_feature_names_out())

Vocabulary: ['again' 'and' 'cricket' 'like' 'lot' 'movie' 'people' 'watch']
